### PR TITLE
Move logic to app.jsx

### PR DESCRIPTION
**Pull request by thomasjinlo**

### CODE REVIEW

**Comment by kennethlee** [comment]
Whoopsie, I somehow missed this PR.

Merging this would pollute the repo by adding all the node modules, which is not what we want. Can you create a separate commit for a .gitignore with /node_modules/  added to it?

**Comment by thomasjinlo** [comment]
Hopefully this fixes it

**Comment by kennethlee** [comment]
You'll prob have to create another commit with the entire node_modules dir removed

**Comment by thomasjinlo** [comment]
Got rid of node_modules dir

**Comment by kennethlee** [comment]
Merged, yo.

**Pull request merged**
